
service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  - serverless-dynamodb-local
  - serverless-offline

#
#  - serverless-dynamodb-local


defaults:
  stage: dev
  region: us-east-1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip


functions:
  home:
    handler: homeHandler.home


    events:
      - http:
          path: home
          method: get
          response:
             headers:
               Content-Type: "'text/html'"
             template: $input.path('$')

  delivery:
    handler: lib/users/usersHandler.users

    events:
      - http:
          path: users/getUsers
          method: get
          request: ${file(./templates.yml):request}

      - http:
          path: users/createUser
          method: post
          request: ${file(./templates.yml):request}
      - http:
          path: users/getUser
          method: post
          request: ${file(./templates.yml):request}










#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    newResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: newBucket
