# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
#defaults:
#  stage: dev
#  region: us-east-1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip
plugins:
- serverless-offline

functions:
  home:
    handler: homeHandler.home


    events:
      - http:
          path: home
          method: get


  delivery:
    handler: user/userHandler.user

    events:
      - http:
          path: users/getUsers
          method: get
          request: ${file(./templates.yml):request}
      - http:
          path: users/createUser
          method: post
          request: ${file(./templates.yml):request}
      - http:
          path: users/getUser
          method: post
          request: ${file(./templates.yml):request}









#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    newResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: newBucket
